### ISSUE TITLE
Error running the script 

### ISSUE THREAD

**Issue by ankitkotnala** [INGourav/Azure-Resources#3]
While running the script I get below error : 

The alias "User or Group GUID" is declared multiple times.
    + CategoryInfo          : MetadataError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AliasDeclaredMultipleTimes

**Comment by INGourav** [comment]
Thanks for the issue @ankitkotnala, we have taken this under consideration and this has been fixed now.
Please feel free to raise the bug(s) and other feedback in the future too
